name: D.J. Soto
favicon: null
layout_spectrum: 0.49305
typography_spectrum: 0.74965
title: D.J. Soto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0502'
    - '#2f5f91'
    - '#efdbbe'
    - '#8e8579'
    - '#9a422c'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
